### PR TITLE
haw-hamburg:0.1.0

### PR DESCRIPTION
**Pull request by LasseRosenow**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: This allows Typst users to write their bachelor or master thesis using the design of the haw-hamburg.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [ ] `exclude`d PDFs or README images, if any, but not the LICENSE

- [x] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by LasseRosenow** [comment]
I haven't excluded some PDFs from examples so users can have a fast view how the template looks like.
I saw that many packages have example PDFs. If you  think I should remove them, I can remove them of course.

**Comment by elegaanz** [comment]
Because you excluded the whole `examples` directory, the PDF files are excluded as well. And it makes sense to do so in my opinion, because these files are not necessary to have in the local cache for the package to work correctly (and most people will have a look in your GitHub repo if they want to see the examples, not in the package cache on their machine).

The bot listed a few variables and functions that are not named following Typst conventions, but you can choose to ignore these warnings if you want to, tell me what you prefer.

**Comment by LasseRosenow** [comment]
Thanks for letting me now, I have just fixed all the warnings :)
I always try to adhere to the naming conventions of course, but still need to get used to it :)

**Comment by elegaanz** [comment]
Thank you for making the changes, and for the package :)

**Pull request merged**
