### PR TITLE
scienceposters:0.2.0

### PR DESCRIPTION
**Pull request by jonaspleyer**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: This package easily allows researches to build up nice posters while having lots of options to customize them.
We also include functionality to stretch boxes such that they fill out remaining unused space. (lots of implementation work here)

The [documentation](https://jonaspleyer.github.io/typst-scienceposters/) of the package is generated by hugo externally.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

### CODE REVIEW

**Comment by laurmaedje** [comment]
Thanks for the submission!

I took a quick peek and came to the conclusion that this is a template more than a package. That's totally fine, but it means that the PR will still be blocked for some time (probably a few weeks) while we build out some infrastructure around templates.

The name is also a bit too obvious and canonical for what the package does. Since we haven't published naming guidelines for templates yet though, it might make sense to wait for that until picking a new name.

On a final note, `kebab-case` is generally more common and idiomatic for Typst code, in case you want to adopt that convention for the package.

**Comment by jonaspleyer** [comment]
Thanks for the immediate feedback. I was not aware that there is also a template packaging system coming up. Speaking from a functionatliy perspective, this package does not modify any existing show rules or predefined functions. Instead it simply offers additional functionality to define boxes. If this is still considered to be a template, I am more than happy to wait until the proper infrastructure is up.

I also notices that my package actually contains an error with the naming in the `typst.toml` file. I will fix this.
Furthermore, I am happy to change the name to `science-posters` for now. I am happy to review this name once naming guidelines are defined.

Thanks for your time.

**Comment by laurmaedje** [comment]
Oh sorry, I wasn't very clear. I didn't mean kebab case for the package name but rather for the functions in the package. Name can be kebab case too though of course.

**Comment by laurmaedje** [comment]
Templates will also be packaged in this registry, but they will have some extra metadata to make them a nicer experience to set up.

**Comment by jonaspleyer** [comment]
> Oh sorry, I wasn't very clear. I didn't mean kebab case for the package name but rather for the functions in the package. Package name can be kebab case too though of course.

Okay I will keep this in mind for the next version (0.3.0).

**Comment by laurmaedje** [comment]
We now accept templates into the repository. The updated README details what changes need to be done for a package to become a template. You can try your template package locally with the new `typst init` command by compiling the latest Typst compiler from the main branch. Alternatively, you can wait a bit until the next release drops. If there are any questions or something is unclear with the new process, please point this out. Thank you for your patience!

**Comment by jonaspleyer** [comment]
Thanks for the notice. I will look into this in the coming days. Might take me some time though.

**Pull request closed without merging**
