### PR TITLE
use caption body to avoid "Agorithm 1: Algorithm 1"

### PR DESCRIPTION
**Pull request by Oyveloper**
I am submitting
- [ ] a new package
- [ x ] an update for a package

Description: Since the caption by default also uses the supplement, the current code shows double "Algorithm n". Using only the caption body fixes the issue

### CODE REVIEW

**Comment by CGMossa** [comment]
I'd this your package?

**Comment by Oyveloper** [comment]
@CGMossa not my package, but the issue bugged me. ended up using the altered version in my thesis, but figured I'd contribute back for others to use

**Comment by Oyveloper** [comment]
Oh, I thought this was that repo, sorry. I'll find the original repo instead

**Comment by Oyveloper** [comment]
Turns out this change is actually implemented in the source repo, but not updated here

**Comment by laurmaedje** [comment]
okay, I'm gonna close this then

**Pull request closed without merging**
