### PR TITLE
scienceicons:0.0.6

### PR DESCRIPTION
**Pull request by rowanc1**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: This is a package for various SVG icons that are used in for open-science articles (license information, open-access badges, ROR identifiers, Orcid ID, Jupyter logos, etc.). The contents only includes the SVG icons and a helper function to use it appropriately in typst (positioning and re-coloring), there are exactly the same icons in `react` and `vue` hosted on npm with the same name.

These are used to create the following types of layouts in typst:

image

image

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

### CODE REVIEW

**Comment by laurmaedje** [comment]
I'm on the fence with this one, but I think the name is too obvious/canonical as is, in particular, since it mirrors an npm package with the same name. Do you have any ideas for a bit more unique name?

**Comment by rowanc1** [comment]
The NPM packages are built from the same source and will remain in sync, which is why it would be nice to have the same name. If that is not possible, maybe `sci-icons`?

**Comment by laurmaedje** [comment]
Okay, I quickly discussed with @reknih (the naming guidelines are a bit subjective after all) and he didn't find it too obvious, so I'm okay with it, too!

**Comment by rowanc1** [comment]
Awesome, that is fantastic! Really excited to get started with these and some other typst packages I am working on:

image

Is there anything else necessary before releasing it?

**Comment by laurmaedje** [comment]
> Is there anything else necessary before releasing it?

Nope. :)

**Comment by rowanc1** [comment]
Awesome, thanks for the quick merge! 🚀

**Comment by laurmaedje** [comment]
That screenshot looks awesome!

**Comment by rowanc1** [comment]
Thanks - really enjoying using typst and actually being able to style things professionally. :)

Template is over here:
https://github.com/LaPreprint/typst

Looking to do some simplifications so I can reuse components in various other similar templates for books and some community journals.

**Pull request merged**
