### PR TITLE
quill:0.2.0

### PR DESCRIPTION
**Pull request by Mc-Zen**
I am submitting
- [ ] a new package
- [x] an update for a package

This update adds new features and fixes some bugs introduced by breaking changes in recent Typst versions. 

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name in conformance with the guidelines
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] ensured that my submission does not infringe upon the rights of a third party
- [x] tested my package locally on my system and it worked
- [x] named this PR as `name:version` of the submitted package
- [x] agree that my package will not be removed without good reason

### CODE REVIEW

**Comment by Mc-Zen** [comment]
Hi @laurmaedje ,

I think something is wrong. Just importing the new version, `#import "@preview/quill:0.2.0"` already results in the error essage 

`failed to decompress package (unexpected end of file)`

Could you look into the issue? Before submission I tested the package locally and everything worked fine.

**Comment by laurmaedje** [comment]
I can't reproduce the error. It works for me both locally and in the web app.

**Comment by Mc-Zen** [comment]
It does indeed work locally

**Comment by Mc-Zen** [comment]
The error in the Web App occurs only in Microsoft Edge and only in exactly one (my main) user profile. Incognito mode and other profiles work fine. I'll wait and see if the issue is resolved by itself. Restarting the computer did not help.

**Comment by laurmaedje** [comment]
Maybe wrong data is saved in your browser cache? Although I don't know where that wrong data would come from.

**Comment by Mc-Zen** [comment]
I suppose that was the case, clearing the cache resolved the issue 👍

**Pull request merged**
