### PR TITLE
edgeframe:0.1.0 and pigmentpedia:0.1.0

### PR DESCRIPTION
**Pull request by neuralpain**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: Two new packages:
1. palette - an extended color library for Typst,
2. paperparam - a package with basic config values for page setup/layout. This will be expanded in the future as I discover more needs.

I've been using these in my personal documentation so I decided to release publicly for anyone to use. I plan to add some odd color values to `palette` later for easier access to uncommon colors.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

### CODE REVIEW

**Comment by elegaanz** [comment]
Hello, and thank you for submitting these packages. I feel like their names are bit too descriptive of what they are, especially for `palette`. Could you please change them to something more unique?

**Comment by neuralpain** [comment]
I'm open to changing `paperparam` to `edgeframe` (as vague as I could get within context); and `palette` to `pigmentpedia`, a play on "pigment" and "encyclopedia". How does that sound?

**Comment by elegaanz** [comment]
Great :) thank you!

**Comment by neuralpain** [comment]
The package names were updated and ready for another review.

**Comment by elegaanz** [comment]
Thanks!

**Pull request merged**
