### PR TITLE
basalt-backlinks:0.1.0

### PR DESCRIPTION
**Pull request by GabrielDTB**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: This package provides an interface to generate and get the backlinks for a particular label. That is, it lets you get the locations of links which point to a certain label.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

- [ ] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by elegaanz** [comment]
Thanks :)

**Comment by neuralpain** [comment]
> This package provides an interface to generate and get the backlinks for a particular label. That is, it lets you get the locations of links which point to a certain label.

@GabrielDTB I believe this information should be included in the package's official documentation. I didn't fully understand it's purpose before reading this description.

**Comment by GabrielDTB** [comment]
@neuralpain Thanks for the feedback. Where in the README would you recommend including that line?

**Comment by neuralpain** [comment]
I think placing it just before the code block would be fine.

**Pull request merged**
