### PR TITLE
babel:0.1.1

### PR DESCRIPTION
**Pull request by rwmpelstilzchen**
I am submitting
- [x] a new package
- [ ] an update for a package

This my first Typst package 🎉
I hope everything is done according to the required structure 🙂

Description: This package provides functions that replace actual text with random characters, which is useful for redacting confidential information or sharing the design and structure of an existing document without disclosing the content itself. A variety of ready-made sets of characters for replacement are available (75 in total; termed alphabets), representing diverse writing systems, codes, notations and symbols. Some of these are more conservative (such as emulating redaction using a wide black pen) and many are more whimsical.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

### CODE REVIEW

**Comment by SolidTux** [comment]
I don't think `babel` is a good choice for a name, as people would probably expect it to do something similar to the equally named LaTeX package.

**Comment by rwmpelstilzchen** [comment]
@SolidTux
Please read § I.2 in the [manual](https://codeberg.org/afiaith/babel/releases/download/0.1.0/manual.pdf).

**Comment by elegaanz** [comment]
Thank you for the package. I think the name is fine. If too many people complain that this package is not related to the LaTeX babel package, a disclaimer could easily be added to the README, to redirect them to an actual alternative.

**Comment by rwmpelstilzchen** [comment]
Thanks! 😊

**Pull request merged**
