### PR TITLE
silver-dev-cv:1.0.0

### PR DESCRIPTION
**Pull request by conanbatt**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: This is a resume designed for remote software developers. We use it to update the resume of candidates that go through our talent agency (https://silver.dev). Currently we recommend a set of resumes from typst, this one is more streamlined.

I have read and followed the submission guidelines and, in particular, I
- [X] selected a name that isn't the most obvious or canonical name for what the package does
- [X] added a `typst.toml` file with all required keys
- [X] added a `README.md` with documentation for my package
- [X] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [X] tested my package locally on my system and it worked
- [X] `exclude`d PDFs or README images, if any, but not the LICENSE

- [X] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by conanbatt** [comment]
The warning is about using a font amply used in other packages, so assuming it is ok.

**Comment by conanbatt** [comment]
@elegaanz Would love to get some feedback / if it's possible to get it merged. I'm excited to land this template for my community!

**Comment by conanbatt** [comment]
Gotcha. I have no issues changing the name to accommodate guidelines. I was following this instruction:

```
Additional guidance for template packages: It is often desirable for template names to feature the name of the organization or publication the template is intended for. However, it is still important to us to accommodate multiple templates for the same purpose. Hence, template names shall consist of a unique, non-descriptive part followed by a descriptive part. For example, a template package for the fictitious American Journal of Proceedings (AJP) could be called organized-ajp or eternal-ajp. Package names should be short and use the official entity abbreviation. Template authors are encouraged to add the full name of the affiliated entity as a keyword.
```

If we want it abbreviated it would be sd_cv (strange?) or silver_cv. Thanks for your response.

**Comment by elegaanz** [comment]
After discussion, the name is fine :)

**Pull request merged**
