### PR TITLE
tablem:0.1.0

### PR DESCRIPTION
**Pull request by OrangeX4**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: Write markdown-like tables easily.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name in conformance with the guidelines
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] ensured that my submission does not infringe upon the rights of a third party
- [x] tested my package locally on my system and it worked
- [x] named this PR as `name:version` of the submitted package
- [x] agree that my package will not be removed without good reason

### CODE REVIEW

**Comment by laurmaedje** [comment]
We've clarified the naming rules a bit recently to make it easier to follow:

> Package names should not be the obvious or canonical name for a package with that functionality

Based on this new phrasing, I would say that that "mdtable" (alongside "markdown-table") is definitely among the most obvious names for this functionality. Could you add a little more uniqueness to the name?

**Comment by OrangeX4** [comment]
Thanks for reply!


How about "tablem"or "tabla"?



---Original---
From: ***@***.***&gt;
Date: Thu, Nov 16, 2023 18:07 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [typst/packages] mdtable:0.1.0 (PR #238)




 
We've clarified the naming rules a bit recently to make it easier to follow:
  
Package names should not be the obvious or canonical name for a package with that functionality
  
Based on this new phrasing, I would say that that "mdtable" (alongside "markdown-table") is definitely among the most obvious names for this functionality. Could you add a little more uniqueness to the name?

**Comment by laurmaedje** [comment]
Those would be fine.

**Comment by OrangeX4** [comment]
Ok, I have renamed it to "tablem". Thanks!

**Comment by laurmaedje** [comment]
Thank you!

**Pull request merged**
