### PR TITLE
quick-minutes:1.0.0

### PR DESCRIPTION
**Pull request by Lypsilonx**
Description: Quick Minutes is a template for taking quick notes in a meeting and recording times, events, votes etc. with intelligent error detection and name/time recognition

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] excluded PDFs or README images, if any, but not the LICENSE

- [x] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by elegaanz** [comment]
Hello. The file in your template does emits a warning when compiling (`layout did not converge within 5 attempts`). It would be nice if you could fix it so that people have a fully working project when they start from your template.

**Comment by Lypsilonx** [comment]
I cannot for the life of me figure out what the source for that is... as you can see some of the commits suddenly converged when I didn't even change anything relating to states. If anyone could give me a pointer as to where I should look. But this problem has been there from the beginning :(

**Comment by Lypsilonx** [comment]
I figured it out... I hope I didn't break anything along the way

**Comment by elegaanz** [comment]
Thanks! If you realize something is not working anymore, you can always make a patch release later.

**Pull request merged**
