### PR TITLE
blindex:0.1.0

### PR DESCRIPTION
**Pull request by cnaak**
I am submitting
- [ X ] a new package
- [ ] an update for a package

Description: Index-making of Biblical literature citations in Typst. The functionality achieved by this package is unique in the Typst ecosystem and useful for theologians or anyone citing biblical literature.

I have read and followed the submission guidelines and, in particular, I
- [ X ] selected a name that isn't the most obvious or canonical name for what the package does
- [ X ] added a `typst.toml` file with all required keys
- [ X ] added a `README.md` with documentation for my package
- [ X ] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [ X ] tested my package locally on my system and it worked
- [ X ] `exclude`d PDFs or README images, if any, but not the LICENSE anda small thumbnail.

- [ X ] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by cnaak** [comment]
Test scope seem to include other packages, which is quite unexpected. Probably because I kept my fork in sync with upstream (are devs not supposed to do that?)
My package is failing, but I want to apply a fix in an unsync'd fork, so I guess the best course of action is to close this PR and start anew once I'm ready... sorry for the dust.

**Comment by cnaak** [comment]
Test scope seem to include other packages, which is quite unexpected. Probably because I kept my fork in sync with upstream (are devs not supposed to do that?)

My package is failing, but I want to apply a fix in an unsync'd fork, so I guess the best course of action is to close this PR and start anew once I'm ready... sorry for the dust.

**Comment by elegaanz** [comment]
No worries :) The CI runs for all packages, this is expected behavior. It is better to keep your fork in sync with upstream, but not mandatory for this repository (as you are only supposed to create new files when submitting a package, which should always be trivial to merge and should not conflict, regardless of the point of history you are based on).

**Comment by cnaak** [comment]
> No worries :) The CI runs for all packages, this is expected behavior. It is better to keep your fork in sync with upstream, but not mandatory for this repository (as you are only supposed to create new files when submitting a package, which should always be trivial to merge and should not conflict, regardless of the point of history you are based on).

Thank you for the clarifications!!

**Pull request closed without merging**
