### PR TITLE
gentle-clues:0.1.0

### PR DESCRIPTION
**Pull request by jomaway**
I am submitting
- [x] a new package
- [ ] an update for a package

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name in conformance with the guidelines
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] ensured that my submission does not infringe upon the rights of a third party
- [x] tested my package locally on my system and it worked
- [x] named this PR as `name:version` of the submitted package
- [x] agree that my package will not be removed without good reason

Description: Simply add some admonishments in your typst documents. (Predefined or define your own)

### CODE REVIEW

**Comment by laurmaedje** [comment]
I was just wondering whether "admonishments" is the correct terminology, but you'll be the final judge of this. 

However, my main concern is that both admonish and admonitions are too descriptive names for the package (with respect to the Typst package naming guidelines). Packages names should not be merely descriptive so that there are level playing grounds for all package submitters (if someone else wanted to make a similar package in the future).

**Comment by jomaway** [comment]
Ok I understand your concerns. I will rename it tomorrow. I came up with the name `gentle-clues`. Hope this one is ok with the guidelines. 😉

**Comment by laurmaedje** [comment]
That sounds good!

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
