### PR TITLE
glossarium:0.4.2

### PR DESCRIPTION
**Pull request by quachpas**
I am submitting
- [ ] a new package
- [x] an update for a package

## 0.4.2

> [!TIP]
> For Typst v0.12.0 and later
> A new function is introduced `register-glossary`.
> Recommended usage is the following:
> ```diff
>  #import "@preview/glossarium:0.4.0": make-glossary, register-glossary, print-glossary, gls, glspl
>  #show: make-glossary
> + #let entry-list = (...)
> + #register-glossary(entry-list)
> ... // Your document body
>  #print-glossary(
> - (
> -   ...
> - )
> +  entry-list
>  )
> ```

> [!NOTE]
> Deprecate `location` argument in queries

> [!TIP]
> `short` is no longer **required**, but **semi-optional**.
> Accept `short` or `long` for an entry, but not neither.

### CODE REVIEW

**Comment by quachpas** [comment]
> @slashformotion You released glossarium:0.4.1, so you probably want to have a look at this pull request. If you want this update to be merged, please leave a comment stating so. Without your permission, the pull request will not be merged.

Slash is no longer the maintainer for glossarium. It has been transferred to typst-community, and I am continuing his work. Unsure if he will respond, see https://github.com/orgs/typst-community/discussions/11#discussioncomment-10812940.

**Comment by elegaanz** [comment]
Thanks for the info :) If you could just fix the name of the LICENSE file, it should be good to merge afterwards.

**Comment by elegaanz** [comment]
Thank you :)

**Comment by slashformotion** [comment]
LGTM

**Pull request merged**
