### PR TITLE
idwtet

### PR DESCRIPTION
**Pull request by ludwig-austermann**
I am submitting
- [x] a new package
- [ ] an update for a package

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name in conformance with the guidelines
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] ensured that my submission does not infringe upon the rights of a third party
- [x] tested my package locally on my system and it worked
- [x] named this PR as `name:version` of the submitted package
- [x] agree that my package will not be removed without good reason

Description: This package lets developers write better demonstration code, as it adds special code blocks `typst-ex`, which highlights and displays itself as typst code blocks, but also evaluates itself. By this, examples should never be out of date and gain additionally unified design.

### CODE REVIEW

**Comment by laurmaedje** [comment]
Just wanted to note that it's possible to evaluate non-code by doing `eval("[" + markup + "]")`.

**Comment by ludwig-austermann** [comment]
> Just wanted to note that it's possible to evaluate non-code by doing `eval("[" + markup + "]")`.

I don't quite understand what you mean by that. If I understand correctly, this can not be applied in the package, or can something be simplified? Maybe, to clarify the use case:

ouset_and_funarray

**Comment by laurmaedje** [comment]
> To express the locality (and because it is still impossible to evaluate non code), each code block starts in code mode and is also thus displayed as such. (A `#{` and a`}` are added accordingly.)

I was commenting on this, specifically on the "and because it is still impossible to evaluate non code" part. Maybe I misunderstood what you mean with it.

**Comment by laurmaedje** [comment]
Also, it's actually not intentional that package imports work in `eval`. Normal imports don't. I need to think a bit about whether there is a problem with allowing it (maybe not, but my instinct and Python's eval tell me be careful).

**Comment by ludwig-austermann** [comment]
Ah yes that makes sense, thanks. I just rewrote some parts and will improve on the design.

**Comment by ludwig-austermann** [comment]
In my package, one would have to define all imports outside then, with no checking, if the imports are indeed correct in the examples.

**Comment by laurmaedje** [comment]
I don't follow. If the imports are outside, then you couldn't access anything inside the `eval` as it doesn't have access to the surrounding scope.

**Comment by ludwig-austermann** [comment]
Oh, I see, I never actually tested that. Well, the package, for sure, wouldn't be as useful. Maybe one should be able to specify which variables `eval` can access from outside? (Python does this, but python is not famous for its best and well thought through language design)

Anyway, I will change the README accordingly.

**Comment by laurmaedje** [comment]
I'll mark this as draft until the import situation is cleared up.

**Pull request closed without merging**
