### PR TITLE
polytechnique-reports:0.1.2

### PR DESCRIPTION
**Pull request by remigerme**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: a template following École polytechnique's guideline for internship reports. Currently matching the design of the LaTeX existing template (some non-essential features aren't available yet, they'll be pushed after). Made to be used by students who will prefer Typst over LaTeX.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

- [x] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by elegaanz** [comment]
Hi! I feel like your package does not fit [our naming conventions](https://github.com/typst/packages/?tab=readme-ov-file#submission-guidelines). Could you please change it for something more unique? Adding an adjective in front of the current name is enough if you don't have any better idea.

**Comment by remigerme** [comment]
Hi, no problem, will `typographix-polytechnique-reports` suit you ? (TypographiX is the name of the student club which handles school templates.)

Moreover, I'm new to OSS and I have a question about the recommended behavior when PR. I tend to commit a lot (like, maybe, perhaps, a bit too much) when I'm working on the template ([link to the original repository](https://github.com/remigerme/typst-polytechnique)). My question is : will this flood and pollute Typst packages git history ? I feared it would so I squashed before PR but maybe it is unnecessary on my side ?

**Comment by elegaanz** [comment]
Yes, this name would work :)

And for the squashing, GitHub offers an option to squash automatically when merging (which is enabled for this project), so you don't have to do it yourself.

**Comment by remigerme** [comment]
Ok nice, thank you !

I'll create another PR in a few minutes with the new name and the "unsquashed" git history (it'll be easier for me to work on my fork) :)

**Pull request closed without merging**
