### PR TITLE
matryoshka:0.1.0

### PR DESCRIPTION
**Pull request by freundTech**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: Explain what the package does and why it's useful.

matryoshka,  named after the famous nesting dolls, is a Typst package that bundles a full Typst compiler as a Typst plugin.
It is useful for documentation authors, that might want to show Typst source code side-by-side with the documents it produces in their documents.

Also it's just cool that it's possible :wink: 

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

- [ ] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by freundTech** [comment]
Note that the wasm plugin binary is quite big at 27.7MB. I hope that this can still be accepted.

**Comment by Enivex** [comment]
This is a chonky boi

**Comment by NiklasEi** [comment]
@freundTech did you already try using [wasm-opt](https://github.com/WebAssembly/binaryen?tab=readme-ov-file#tools) to reduce the file size?

Maybe there could be an API to supply additional packages to this package? Then I would see a lot of use for writing documentation as you mentioned.

**Comment by freundTech** [comment]
I tried wasm-opt, which only got it to 19MB. I'm looking into some other ideas right now.

I'm not sure if supplying packages will be possible. I'll have to look into how exactly they are loaded. Supplying extra files (for include or imports not starting with `@`) is already possible.

**Comment by elegaanz** [comment]
I'm closing this PR for now, if you make any progress feel free to re-open it (or another one).

**Pull request closed without merging**
