### PR TITLE
gqe-lemoulon-presentation:0.0.4

### PR DESCRIPTION
**Pull request by OlivierLangella**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: The package offers a customized polylux theme based on "clean-theme". It is tailored to help researchers in our lab to create slides automatically with the same template.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

- [x] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by OlivierLangella** [comment]
I've fixed the errors and warnings displayed by the tests.
There is a lot warnings remaining depending from the polylux package.

**Comment by OlivierLangella** [comment]
Unfortunately, there is a check failure due to polylux:0.3.1 package warnings compiling with 0.12.0.
Should I wait for an update of the polylux package ?

**Comment by elegaanz** [comment]
It is up to you, but I would personally wait for Polylux to be updated if you are not in a hurry.

**Comment by OlivierLangella** [comment]
oh yes, that's wise, I will wait ;)
by the way, I'm really enthusiastic about typst, great work, thank you very much !

**Comment by OlivierLangella** [comment]
Hello,
finally, it seems that "touying" is better maintained, so I've switch my template from polylux to touying.
This one does not produce warnings.

Is it possible to forget gqe-presentation 0.0.1 and jump directly to the new "touying" based 0.0.3 ?

Thank you very much
Olivier

**Comment by OlivierLangella** [comment]
Ok, thanks, I've deleted the previous version.

There is no problem to change the name of my package. Indeed, GQE is the name of our laboratory. It is very specific and may be not relevant for other user that may work in the same field.

Do you have a suggestion for this specific case and a good package name avoiding misunderstanding ?

Thanks again
Olivier

**Comment by OlivierLangella** [comment]
That's fine, thanks for the suggestion. I can rename it "gqe-lemoulon-presentation" if it is not too long or "lemoulon-presentation" otherwise.
Thank you very much for your hyper fast responsivity and the possibility to add the package to the central repository.
It will be far more easier for people in my lab.

**Comment by elegaanz** [comment]
"gqe-lemoulon-presentation" would be fine.

**Comment by elegaanz** [comment]
Thank you!

**Pull request merged**
