### PR TITLE
finite:0.1.0

### PR DESCRIPTION
**Pull request by jneug**
I am submitting
- [x] a new package
- [ ] an update for a package

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name in conformance with the guidelines
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] ensured that my submission does not infringe upon the rights of a third party
- [x] tested my package locally on my system and it worked
- [x] named this PR as `name:version` of the submitted package
- [x] agree that my package will not be removed without good reason

`finite` is build on top of CeTZ and draws transition diagrams of finite state machines / automata.

### CODE REVIEW

**Comment by laurmaedje** [comment]
This looks really cool! One small thing: I just looked at the manual and saw that a few of the imports lack closing quotes (in section I.1).

**Comment by jneug** [comment]
> This looks really cool! One small thing: I just looked at the manual and saw that a few of the imports lack closing quotes (in section I.1).

Good catch. The manual need some work in general. (I should stop writing documentation in the middle of the night. 😅) I will do some work on the manual over the weekend and push a new version. Maybe I will change some of the argument names, too. 

So you might want to wait with a merge till then.

**Comment by jneug** [comment]
I did some work on the package and think it should be ready for a first release now.

**Comment by laurmaedje** [comment]
Thank you!

**Pull request merged**
