### PR TITLE
datify:0.1.1

### PR DESCRIPTION
**Pull request by Jeomhps**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: Datify is a simple date package that allows users to format dates in new ways and addresses the issue of lacking date formats in different languages.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

### CODE REVIEW

**Comment by Jeomhps** [comment]
Hello,

This is my first time making a pull request. I hope I understood everything correctly and didn't make any mistakes !

**Comment by Enter-tainer** [comment]
> selected a name that isn't the most obvious or canonical name for what the package does

you may want to select another name that meet the requirement

**Comment by Nicoloutree** [comment]
Would datify respect the rules ?

**Comment by reknih** [comment]
> Hello, would datify respect the rules ?

That works!

**Comment by Jeomhps** [comment]
Hi, it should be good now, I just changed the name of the packages and all occurences of the name has been changed throughout the different files.

**Comment by elegaanz** [comment]
Thanks for changing the name.

Just a remark before this gets merged: Typst packages generally use kebab-case for function and variable names, not camelCase. But the choice is yours, if you prefer camelCase, I can merge this PR as is.

**Comment by elegaanz** [comment]
Okay, no problem. LGTM then.

**Pull request merged**
