### PR TITLE
aloecius-aip:0.0.1

### PR DESCRIPTION
**Pull request by Raunak12775**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: This is a template for `American Institute of Physics` (AIP) journal articles (draft version) targeted mainly to computational chemistry group of people. This is an inspired template and not an official one. There was nothing related to AIP journals submitted in typst repositories. I feel it is benficial to keep it there as it is one of the most popular journals for computational chemists as well as for physicists where they submit their work.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

- [x] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by elegaanz** [comment]
Thanks :)

**Comment by Raunak12775** [comment]
Hello, Thanks for accepting my PR. I am very new to github PR. I might have a naive question: when will I see my template online for typst web app?

**Comment by elegaanz** [comment]
It should already be available for use in the web app (the CI published it as soon as the PR was merged), but Typst Universe is only refreshed once a day, so it may take up to 24 hours before it is listed here.

**Comment by Raunak12775** [comment]
Thanks a lot @elegaanz have a nice day.

**Pull request merged**
