### PR TITLE
mathtext:0.0.1

### PR DESCRIPTION
**Pull request by chengluyu**
I am submitting
- [x] a new package
- [ ] an update for a package

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name in conformance with the guidelines
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] ensured that my submission does not infringe upon the rights of a third party
- [x] tested my package locally on my system and it worked (see https://typst.app/project/rKb66eanDkWAXrJYvP0mtF)
- [x] named this PR as `name:version` of the submitted package
- [x] agree that my package will not be removed without good reason

Description: Explain what the package does and why it's useful.

### CODE REVIEW

**Comment by chengluyu** [comment]
### Sneak Peek

**Preview**
image

**Source**
```typst
With `mathtext`:

- $textsc("Equation") a x + b y + c = 0$
- $textit("Equation") a x + b y + c = 0$
- $textbf("Equation") a x + b y + c = 0$
- $textrm("Equation") a x + b y + c = 0$

Without `mathtext`:

- $#smallcaps("Equation") a x + b y + c = 0$ does not work at all.
- $italic("Equation") a x + b y + c = 0$ does not use the document font.
- $bold("Equation") a x + b y + c = 0$ does not use the document font.
- $upright("Equation") a x + b y + c = 0$ does not use the document font.
```

Also, I'm happy to be the first person to submit the Typst package. 😄

**Comment by Enivex** [comment]
As far as I can see this doesn't actually do what it claims to do. It does not use the document font, but some fallback.

**Comment by chengluyu** [comment]
> As far as I can see this doesn't actually do what it claims to do. It does not use the document font, but some fallback.

Nice catch! I'm always using Linux Libertine and didn't realized it's a Typst's fallback.

**Comment by laurmaedje** [comment]
I am going to close this because it doesn't work (as already discussed). The font handling is something that needs to be fixed in the compiler.

**Pull request closed without merging**
