### PR TITLE
athena-tu-darmstadt-exercise:0.1.0

### PR DESCRIPTION
**Pull request by FussballAndy**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: This is an unofficial exercise template for the University TU Darmstadt (Technische Universität Darmstadt) following the design guidelines and imitating the official LaTeX template.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

- [x] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by FussballAndy** [comment]
Please note that the current image in the README does not match the provided image in the preview folder. The reason for this is that the image in the README points to the image file within the repository. However once this template is ready to get submitted [this](https://github.com/JeyRunner/tuda-typst-templates/pull/8) PR will get merged and change the image to the current version. If this is not wanted I can change the README to use the image in preview.

**Comment by elegaanz** [comment]
It's fine to have the images in the README reference the original repository I think.

As for the template not compiling however, this will need to be fixed, we want to guarantee that all projects created from templates compile. What you can do is have a fake logo, such as an image that just says "replace me".

**Comment by FussballAndy** [comment]
I added a replacement image. The only failing tests now are kebab casing. However we are currently not planing to change the casing. If that is problematic please let us know.

**Comment by elegaanz** [comment]
No it is not mandatory to use kebab-case, it is just the most common convention for Typst packages and we try to encourage it, but it is up to each package author to decide how they want to name their functions.

Thank you for adding the placeholder logo.

**Pull request merged**
