### PR TITLE
mitex:0.2.2

### PR DESCRIPTION
**Pull request by OrangeX4**
I am submitting
- [ ] a new package
- [x] an update for a package

Description:

1. **Urgent fix:** remove duplicate keys for error when a dict has duplicate keys in 0.11
2. fix: parse bracket/paren group
3. fix: remove extra spacing for ceiling symbols
4. feat: add support for `\(\)` and `\[\]`
5. feat: support footnote and cite

### CODE REVIEW

**Comment by OrangeX4** [comment]
This version doesn't use any of the new features or syntax from version 0.11, so it's best to merge it before 0.11 is officially released. Thanks! :-)

**Comment by laurmaedje** [comment]
> Urgent fix: remove duplicate keys for error when a dict has duplicate keys in 0.11

What exactly do you mean here? This
```typ
#(key: "value", key: "value")
```

was already an error on 0.10.

**Comment by OrangeX4** [comment]
> > Urgent fix: remove duplicate keys for error when a dict has duplicate keys in 0.11
> 
> What exactly do you mean here? This
> 
> ```typst
> #(key: "value", key: "value")
> ```
> 
> was already an error on 0.10.

Yes, so the previous version (like 0.2.1) won't work properly in Typst 0.11. The user needs to switch to 0.2.2

**Comment by OrangeX4** [comment]
> was already an error on 0.10.

Really? However, mitex 0.2.1 will only report errors at 0.11

**Pull request merged**
