### PR TITLE
silky-report-insa:0.1.0

### PR DESCRIPTION
**Pull request by SkytAsul**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: this is a "translation" of the Microsoft Word report template for my engineering school, INSA Rennes. People have been using it for months through my personal repository, now it would be cool to have it on Typst Universe :) 

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

- [x] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by laurmaedje** [comment]
Looks very nice, thanks for the submission! The only problem is that the name is too descriptive as-is. Template names must contain at least one non-descriptive / creative name component so discoverability is a level playing field. (Maybe some other person from an INSA wants to create a template, too.) We recommend the naming schema `<adjective>-insa-report`. See the README for more info.

**Comment by SkytAsul** [comment]
Would `rennes-insa-report` do it in your opinion? Rennes being the city of my INSA. As this is the "official" template being translated to Typst, I can't think of a "creative" adjective :thinking:

**Comment by laurmaedje** [comment]
That wouldn't really fix it. The idea is that there can be more than one version of the official template being translated. There is a bit longer explanation in the [submission guidelines](https://github.com/typst/packages?tab=readme-ov-file#submission-guidelines). You can take a look here for inspiration: https://typst.app/universe/search?kind=templates

**Comment by SkytAsul** [comment]
I see. This one would be fine then.

**Pull request merged**
