### PR TITLE
typpuccino:0.1.0

### PR DESCRIPTION
**Pull request by TeddyHuang-00**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: This simply adds four palette of Catppuccin for use in Typst.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

- [x] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by laurmaedje** [comment]
Since this is a port of an existing project, the name needs to have some unique component beyond the original name, so that another person could potentially also create a port of it. (At least unless you are a maintainer of the upstream project.) This is similar to how we handle plugins that provide bindings to other libraries.

**Comment by TeddyHuang-00** [comment]
> Since this is a port of an existing project, the name needs to have some unique component beyond the original name

Now renamed to ca**typ**uccin, which is close to original while indicating this is for Typst. Is that okay now?

**Comment by laurmaedje** [comment]
It's maybe a _bit_ close so that one could possibly not notice the change, but I think it's okay.

**Comment by TeddyHuang-00** [comment]
How about Typpuccino? Is it better than this one?

**Comment by laurmaedje** [comment]
That would definitely also work. I'll leave it up to you!

**Comment by TeddyHuang-00** [comment]
Renamed to Typpuccino then. Anything else missing here?

**Comment by laurmaedje** [comment]
Nope, all good. Thanks!

**Pull request merged**
