### PR TITLE
note-me:0.3.0

### PR DESCRIPTION
**Pull request by FlandiaYingman**
I am submitting
- [ ] a new package
- [x] an update for a package

Description: Add custom icon support.

### CODE REVIEW

**Comment by FlandiaYingman** [comment]
Oh it's committed as submodule, will fix it later.

**Comment by ngoetti** [comment]
> Oh it's committed as submodule, will fix it later.
How can you create a pull request with the files instead of a submodule. I have not seen that option and also found nothing on stackoverflow which is so weird to me.

**Comment by elegaanz** [comment]
You have to make sure you remove the `.git` folder of your package before adding it to the index when copying your package. With the git command line, the steps to follow would be something like:

```sh
cd typst/packages
cp -r ~/my-package packages/preview/my-package/0.1.0
rm -rf packages/preview/my-package/0.1.0/.git/ # This is the important part, otherwise Git will assume you want to create a submodule, and do it for you
git add packages/preview/my-package/0.1.0/
# Then, commit and push as you would usually do
```

**Comment by FlandiaYingman** [comment]
Thanks! It's done now.

**Comment by elegaanz** [comment]
Thanks

**Pull request merged**
