### PR TITLE
Add CUMCM-typst-template:0.1.0

### PR DESCRIPTION
**Pull request by a-kkiri**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: CUMCM-typst-template is a typst template for China Undergraduate Mathematical Contest in Modeling

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

- [x] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

> This template contains third-party fonts and they are required. I don't know if this is okey. If not, I will close my pull request.

### CODE REVIEW

**Comment by Enter-tainer** [comment]
> This template contains third-party fonts and they are required. I don't know if this is okey. If not, I will close my pull request.

i guess it's not OK. But please dont close this pr. It seems that these fonts are all preinstalled fonts in windows. You may also mention in readme that to make the template works as expected, `<font-list>` is required.

**Comment by Enivex** [comment]
None of the bundled fonts are free. I'm not a lawyer, but I'm guessing this wouldn't be legal.

**Comment by a-kkiri** [comment]
Thanks for your respond, I will resubmit a new version without these fonts and give another way to install these fonts.

**Comment by a-kkiri** [comment]
> > This template contains third-party fonts and they are required. I don't know if this is okey. If not, I will close my pull request.
> 
> i guess it's not OK. But please dont close this pr. It seems that these fonts are all preinstalled fonts in windows. You may also mention in readme that to make the template works as expected, `<font-list>` is required.

Thanks for your respond, I will resubmit a new version without these fonts and give another way to install these fonts.

**Pull request closed without merging**
