### PR TITLE
plotst:0.2.0

### PR DESCRIPTION
**Pull request by Gewi413**
I am submitting
- [ ] a new package
- [X] an update for a package

Updating plotst:
- Fixed Plots overflowing their area
- Fixed * import
- Custom axis formatters (oxifmt)
- Added radar chart

### CODE REVIEW

**Comment by laurmaedje** [comment]
Since plotst 0.1.0 was submitted by @Pegacraft, this would need their permission. (Can also be a blanket permission for all future updates.)

**Comment by Pegacraft** [comment]
> Since plotst 0.1.0 was submitted by @Pegacraft, this would need their permission. (Can also be a blanket permission for all future updates.)

@Gewi413 is a collegue of mine. His submission is fine (and his future ones, too)

**Comment by laurmaedje** [comment]
Could you change the case from `readme.md` to `README.md`? It likely wouldn't matter in a browser setup, but I want to ensure that every package's readme is in a well-known file path.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
