### PR TITLE
tud-corporate-design-slides:0.1.0

### PR DESCRIPTION
**Pull request by jakoblistabarth**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: Presentation template for slides in the corporate design of TUD, Technische Universität Dresden.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

- [x] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by elegaanz** [comment]
Hi. Can you rename your package to something more unique / less descriptive please?

**Comment by jakoblistabarth** [comment]
> Hi. Can you rename your package to something more unique / less descriptive please?

Sure. Sorry for that, I was quite unsure whether the current name would align with your guidelines. However, I did not find it easy to come up with something I felt was better. Would any of these work better?
- `tud-slide-deck`
- `simple-tud-slides`
- `modern-tud-slides`
- `tud-corporate-design-slides`
- `not-tud-ppt`

**Comment by elegaanz** [comment]
Not sure about the first one, but all the others sound good to me, pick the one you like the most.

**Comment by elegaanz** [comment]
Thank you!

**Pull request merged**
