### PR TITLE
pitcher:0.1.0

### PR DESCRIPTION
**Pull request by mielpeeters**
I am submitting
- [x] a new package
- [ ] an update for a package

Pitcher is a tool for creating minimalist and modern presentation slides, with automatic color palette generation and an easy-to-use API.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name in conformance with the guidelines
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] ensured that my submission does not infringe upon the rights of a third party
- [x] tested my package locally on my system and it worked
- [x] named this PR as `name:version` of the submitted package
- [x] agree that my package will not be removed without good reason

### CODE REVIEW

**Comment by sitandr** [comment]
See my comment there in recently merged slides package: https://github.com/typst/packages/pull/229#issuecomment-1802759808.

I think making good framework for slides is hard, so I think it would be really cool if you specify what is the basic difference between your package with `polylux` (very mighty de-facto standard for Typst slides) and `slydst` (recently merged package that claims to be simpler).

The only large feature I noticed with first glance is automatic color palette selection. While it is good, it doesn't justify the whole new package. I'm sure I've missed something important, so I'll be glad to hear more about differences.

**Comment by JamesxX** [comment]
Looking good!

**Comment by andreasKroepelin** [comment]
Definitely not trying to gate keep here but I fail to see in what way this is more than a template for slides and would qualify as a package.

Other than that: `kebab-case` would be great, at least for user facing functions. The slides in the example look very nice, though!

**Comment by laurmaedje** [comment]
As I understand it, this will be upstreamed into polylux. Does that mean this PR here can be closed?

**Comment by mielpeeters** [comment]
Yes it can, i'll close it

**Pull request closed without merging**
