### PR TITLE
modern-cug-report:0.1.0

### PR DESCRIPTION
**Pull request by kongdd**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: Chinese Technical report writing standards.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

- [x] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by elegaanz** [comment]
Hello, and thank you for the package! If you want people to be able to start a project from your `example` directory in the web app or with `typst init`, you can add a `[template]` section to your README (see [the documentation](https://github.com/typst/packages/?tab=readme-ov-file#templates)). If this is not how you expect people to use your package, I can also merge this PR as it is, just tell me.

**Comment by kongdd** [comment]
Thank you @elegaanz. A template has been added.

**Comment by elegaanz** [comment]
Okay, thank you !

**Comment by kongdd** [comment]
Hi @elegaanz , could you tell me how long it will be take before my package come into effect?

**Comment by kongdd** [comment]
Thank u. works now

**Pull request merged**
