### PR TITLE
supercharged-dhbw:3.4.0

### PR DESCRIPTION
**Pull request by DannySeidel**
I am submitting
- [ ] a new package
- [x] an update for a package

**Description:**

- Fix inconsistency in the header spacing (https://github.com/DannySeidel/typst-dhbw-template/issues/19)
- Add option to provide the page numbering style (https://github.com/DannySeidel/typst-dhbw-template/issues/18)
-> find more details on the solution [here](https://forum.typst.app/t/how-to-correctly-display-page-numbering-in-a-custom-footer-with-and-without-total-number-of-pages/2021)
- Update some descriptions in the documentation

### CODE REVIEW

**Comment by DannySeidel** [comment]
@elegaanz the check seems to not be completing. It has now been running for 20 hours ⏱️

**Comment by elegaanz** [comment]
Yes, sorry about that, it crashed for some reason. I restarted it. There are some warnings that you may want to fix.

**Comment by DannySeidel** [comment]
Hi @elegaanz,

I fixed all the warnings I could. The rest are warnings inside the `codelst` package or the problem that `exclude` for folders is not recognize.

**Comment by elegaanz** [comment]
Thanks :)

**Pull request merged**
