### PR TITLE
fletcher:0.1.0

### PR DESCRIPTION
**Pull request by Jollywatt**
I am submitting
- [x] a new package
- [ ] an update for a package

This package is for drawing “diagrams with arrows”, mainly commutative diagrams, finite state machines, and similar things, inspired by `tikz-cd`.

**It is very similar in scope to the `commute` package**, which already exists. This originally started as a fork of that package, but this became a full rewrite. It also depends on `cetz` (unlike `commute`).

Parent repository: ~https://github.com/Jollywatt/arrow-diagrams~ https://github.com/Jollywatt/typst-fletcher

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name in conformance with the guidelines
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
     (A manual is provided with proper documentation.)
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] ensured that my submission does not infringe upon the rights of a third party
- [x] tested my package locally on my system and it worked
- [x] named this PR as `name:version` of the submitted package
- [x] agree that my package will not be removed without good reason

### CODE REVIEW

**Comment by laurmaedje** [comment]
As is, the name falls under "the obvious or canonical name for a package with that functionality". It would be great if you could pick a more unique name for the package.

**Comment by Enivex** [comment]
Can I suggest "Fletcher"?

**Comment by Enivex** [comment]
> I've been stumped by a name, but thinking something like:
> 
> - `arrowfig`
> - `node-conn`
> - `cetz-cd`
> 
> but think they're all bad😅 But why `Fletcher`??

https://www.merriam-webster.com/dictionary/fletcher

> a maker of arrows

**Comment by Jollywatt** [comment]
@Enivex Thanks for the name! 🏹

**Comment by laurmaedje** [comment]
Thank you!

**Comment by Jollywatt** [comment]
Hi @laurmaedje, I just realised I used `#import "@local/cetz:0.1.2"` in one of the source files instead of `#import "@preview/cetz:0.1.2"`, which breaks the package.

What's the best course of action? Can we reopen this PR, or should I make a separate package update PR?

Thanks for your help!

**Pull request merged**
