### PR TITLE
backtrack:1.0.0

### PR DESCRIPTION
**Pull request by TheLukeGuy**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: Backtrack is a simple and performant library that determines the current compiler version and provides an API for comparing, displaying, and observing versions. See [the repository](https://github.com/TheLukeGuy/backtrack) for more details.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name in conformance with the guidelines
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] ensured that my submission does not infringe upon the rights of a third party
- [x] tested my package locally on my system and it worked
- [x] named this PR as `name:version` of the submitted package
- [x] agree that my package will not be removed without good reason

### CODE REVIEW

**Comment by laurmaedje** [comment]
Maybe you could detect Feb 25 through whether `[#1 ;]` has a semicolon and Feb 2 _maybe_ through the heading/list parsing changes. Doesn't really matter, but I was curious whether you tried that already. Also, what do you mean by "Initial releases"? The first true release was Mar 21.

**Comment by TheLukeGuy** [comment]
I did try for a few minutes to detect February 25 using that semicolon fix, but I couldn't find a way to actually test for it since it seems like content values can't be compared until March 21, e.g. [

**Comment by TheLukeGuy** [comment]
I did try for a few minutes to detect February 25 using that semicolon fix, but I couldn't figure out how to test for it automatically since it seems like content can't be checked for equality until March 21. Unless you can think of a different way to test it?

By "initial releases" I meant the private releases that presumably existed before January 30. Sorry if that wording is confusing, I can change it.

Also, sorry for closing the pull request. I tapped the wrong button. 🙃

**Comment by laurmaedje** [comment]
Ah okay, yeah, content was opaque initially. I guess you could call Dec 26 a private release since that was the first time a few preview members could try it. But Jan 30 was just as private since it was still closed preview. Jan 30 was just the first time we wrote a changelog, so there weren't really releases before that, just random changes. :D I think you could just remove the part about the initial releases without it being incorrect.

**Comment by JamesxX** [comment]
Could future Typst releases natively support a version variable? It's a bit late for previous releases so this package would still be useful, but would make knowing the version a more accurate process going forwards.

**Comment by TheLukeGuy** [comment]
Done! I also included a few other documentation changes if that's alright.

**Comment by laurmaedje** [comment]
Thank you!

**Pull request merged**
