### PR TITLE
pointless-size:0.1.0

### PR DESCRIPTION
**Pull request by YDX-2147483647**
I am submitting
- [x] a new package
- [ ] an update for a package

Description:
There is a special size system called 号数制 (hào-system, or number system) for Chinese and Japanese Typesetting, and it is still commonly used in China. The unit is not linearly related to points: 五号 (size 5) = 10.5pt, 小四 (size small 4) = 12pt, 四号 (size 4) = 14pt, … Therefore, people always have to search for a conversion table when `#set text(size: …)` in Typst.

This package hard-codes those conversion rules to allow `#set text(zh(5))` for 五号 (size 5). `zh` is the language code for Chinese, and also an abbr for 字号 zìhào (text size in Chinese).

By the way, CTeX (≈ LaTeX for Chinese) and MS Word support the hào-system natively.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

- [x] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by Enter-tainer** [comment]
iirc it is not recommended to use pinyin for names now.(as it is too obvious or canonical)

**Comment by YDX-2147483647** [comment]
> iirc it is not recommended to use pinyin for names now.(as it is too obvious or canonical)

Thanks, but I find [touying](https://typst.app/universe/package/touying), [tiaoma](https://typst.app/universe/package/tiaoma), [suiji](https://typst.app/universe/package/suiji)…

**Comment by laurmaedje** [comment]
> Thanks, but I find [touying](https://typst.app/universe/package/touying), [tiaoma](https://typst.app/universe/package/tiaoma), [suiji](https://typst.app/universe/package/suiji)…

Those are specifically why we introduced this new rule. The first few got through, but then it got too much. See https://github.com/typst/packages/pull/565#issuecomment-2066850841

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
