### PR TITLE
enunciado-facil-fcfm:0.1.0

### PR DESCRIPTION
**Pull request by bkorecic**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: Worksheet/problemset template for FCFM, University of Chile.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

- [x] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by elegaanz** [comment]
Hello. I don't really speak Spanish, but I feel like the package name is a bit too descriptive of what the package does. If you feel like it's not, can you please translate "enunciados" in English for me, so that I can properly judge? And if you too feel like it is too descriptive, can you please change the package name to something more unique?

**Comment by bkorecic** [comment]
> Hello. I don't really speak Spanish, but I feel like the package name is a bit too descriptive of what the package does. If you feel like it's not, can you please translate "enunciados" in English for me, so that I can properly judge? And if you too feel like it is too descriptive, can you please change the package name to something more unique?

Hello!

Enunciado means "statement" as in "problem statement". I do think it's a bit descriptive, but I think there are more canonical options such as "problemset" or "worksheet", etcetera. I actually first thought of "problemset-fcfm" but then I read the guideline and changed it to a less obvious one. If it's a problem, I can think of a new name.

Thanks for your review!

**Comment by elegaanz** [comment]
Thank you for the translation :) I still think it would be better to change the name to be on the safe side, but you can do the same as most people and add an adjective to the current name, unless you have more inspiration.

**Comment by elegaanz** [comment]
Thank you!

**Pull request merged**
