### PR TITLE
bone-document:0.1.0

### PR DESCRIPTION
**Pull request by zrr1999**
I am submitting
- [x] a new package
- [ ] an update for a package

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name in conformance with the guidelines
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] ensured that my submission does not infringe upon the rights of a third party
- [x] tested my package locally on my system and it worked
- [x] named this PR as `name:version` of the submitted package
- [x] agree that my package will not be removed without good reason

Description: some basic template(resume, document, slides).

### CODE REVIEW

**Comment by istudyatuni** [comment]
> Note: Please do not submit templates as packages just yet

**Comment by laurmaedje** [comment]
I'll mark this as draft until we have infrastructure in-place for template packages.

**Comment by laurmaedje** [comment]
We now accept templates into the repository. The updated README details what changes need to be done for a package to become a template. You can try your template package locally with the new `typst init` command by compiling the latest Typst compiler from the main branch. Alternatively, you can wait a bit until the next release drops. If there are any questions or something is unclear with the new process, please point this out. Thank you for your patience!

**Comment by laurmaedje** [comment]
Thanks for updating the template! There are a few problem with it that would need to be addressed before merging:

- The `set heading(level: 2)` breaks headings (as seen in the screenshot). I'm not sure what the purpose of it is, but I think it can just be removed.

- The emphasis should rule breaks toggling of nested emphasis. Since the font specification in it is redundant with the fonts already specified via `set text`, it can probably be fully removed to fix it.

- It's okay that the template changes the default language and fonts, but then it should specify that in the README and note the target audience and the fonts that users will need. The description in `typst.toml` is also too vague, it should describe what specifically this template is about.

- The README has copy-paste errors from the `ieee` template ("exports the `ieee` function" and the details about the author specification).

- The template doesn't really fit with the `paper` category. You can keep just `report` or add `office`.

- It's not forbidden to say "Powered by BoneDocument" in the footer, but I think it will reduce the usefulness of the template to a general audience that doesn't want this in their document. One compromise would be to allow users to enable or disable this with an argument to the `bone-document` function.

**Comment by laurmaedje** [comment]
I'll close this due to inactivity. Feel free to reopen if you want to continue with it!

**Pull request closed without merging**
