### PR TITLE
in-dexter:0.5.2

### PR DESCRIPTION
**Pull request by RolfBremer**
I am submitting
- [ ] a new package
- [x] an update for a package

Description:
* Fix a bug with bang notation.
* Add compiler version to toml file.
* Migrate deprecated locate to context.
* Support page numbering formats (i.e. roman), when `use-page-counter` is set to
  true. Thanks to @ThePuzzlemaker!
* Suppress extra space character emitted by the `index()` function.
* Fix a bug where math formulas are not displayed.
* Introduce `apply-casing` parameter to `index()` to suppress entry-casing for individual
  entries.

### CODE REVIEW

**Comment by elegaanz** [comment]
Thank you!

**Comment by wlievens** [comment]
Hi, I'm trying to use this version but I get an error:
```
> typst compile myfile.typ
error: package manifest is malformed (version number is missing patch version)
  ┌─ \\?\C:\...\myfile.typ:4:8
  │
4 │ #import "@preview/in-dexter:0.5.2": *
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I'm on Windows using
```> typst --version
typst 0.11.1 (50115102)
```

**Comment by elegaanz** [comment]
Indeed, this version is broken, I didn't notice that the compiler version number was wrong during review. There already is an issue [on the original repository](https://github.com/RolfBremer/in-dexter/issues/19).

**Comment by RolfBremer** [comment]
We fixed that in 0.5.3 and submitted it to the Typst Universe.
Thank you!

**Comment by laurmaedje** [comment]
Note: We had to [adjust this package version](https://github.com/typst/packages/commit/f7cc4b9d15ac0a0eec15be4356b32d5c7de44654) because the package index was broken for everyone:

```
$ typst init @preview/charged-ieee
error: failed to parse package index: Failed to read JSON: version number is missing patch version at line 1 column 128892
```

**Pull request merged**
