### PR TITLE
fauxreilly:0.1.0

### PR DESCRIPTION
**Pull request by dei-layborer**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: A package for creating O'Rly-/O'Reilly-like cover pages.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

### CODE REVIEW

**Comment by elegaanz** [comment]
I'm sorry, but I still feel like the name is too descriptive of what the package does. Can you please change it again to something a bit more unique? If it can help you: it should be original enough so that another package with the same purpose can be submitted, without any of the two being recognized as "more official" or "more canonical". If you don't have much inspiration, you can just add an adjective to the current name, that's what most people do.

**Comment by dei-layborer** [comment]
No problem, and I certainly get what y'all are trying to do in this situation (i.e. keeping package names from being so generic that one person is able to monopolize a given bit of functionality).

Do you have any further thoughts or ideas on what may work?  I've posted to both the discord and the forum asking for suggestions as well, but I figure I need all the help I can get!

**Comment by JKRhb** [comment]
Hmm, not amazingly creative, but how about something like `rly-cool-covers` or `rly-odd-covers`?

**Comment by dei-layborer** [comment]
Is there a way to rename the folder the package is in without downloading the whole repo?  I've been trying to avoid the latter...

**Comment by JKRhb** [comment]
Hmm, I think you can open a web editor by pressing the `.` key in this PR or your fork.

**Comment by dei-layborer** [comment]
That did it!  Changed the folder name and the project name in ``typst.toml``.  Of course let me know if anything else is needed!

**Comment by elegaanz** [comment]
I like the new name! Thank you :)

**Pull request merged**
