### PR TITLE
statastic:0.1.0

### PR DESCRIPTION
**Pull request by Sett17**
I am submitting
- [x] a new package
- [ ] an update for a package

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name in conformance with the guidelines
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] ensured that my submission does not infringe upon the rights of a third party
- [x] tested my package locally on my system and it worked
- [x] named this PR as `name:version` of the submitted package
- [x] agree that my package will not be removed without good reason

Description: Explain what the package does and why it's useful.
Lib to calculate statistical data for arrays and columns of numerical data

### CODE REVIEW

**Comment by Sett17** [comment]
I noticed some things only after creating the PR.
WIP

**Comment by laurmaedje** [comment]
Ready to merge?

**Comment by Sett17** [comment]
> Ready to merge?

yes

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
