### PR TITLE
acrotastic:0.1.1

### PR DESCRIPTION
**Pull request by GaetanLepage**
### I am submitting
- [ ] a new package
- [x] an update for a package

### Description: Explain what the package does and why it's useful.

- Add missing parameter to the 'print-index' function
- Rename `display` to `_display` to avoid clashing with the original typst `display` function

cc @Julian702 

I have read and followed the submission guidelines and, in particular, I
- [ ] selected a name that isn't the most obvious or canonical name for what the package does
- [ ] added a `typst.toml` file with all required keys
- [ ] added a `README.md` with documentation for my package
- [ ] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [ ] tested my package locally on my system and it worked
- [ ] `exclude`d PDFs or README images, if any, but not the LICENSE

- [ ] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by GaetanLepage** [comment]
```
diff '--color=auto' -r 0.1.0/acrotastic.typ 0.1.1/acrotastic.typ
11c11
< #let reset-acronym(acr) = { 
---
> #let reset-acronym(acr) = {
16c16
< #let reset-all-acronyms() = { 
---
> #let reset-all-acronyms() = {
39c39
< #let display(acr, text, link: true) = {
---
> #let _display(acr, text, link: true) = {
57c57
<           display(acr, defs + "s", link: link)
---
>           _display(acr, defs + "s", link: link)
59c59
<           display(acr, defs, link: link)
---
>           _display(acr, defs, link: link)
67c67
<             display(acr, defs.at(0) + "s", link: link)
---
>             _display(acr, defs.at(0) + "s", link: link)
69c69
<             display(acr, defs.at(1), link: link)
---
>             _display(acr, defs.at(1), link: link)
73,74c73,74
<         } else {  
<           display(acr, defs.at(0), link: link)
---
>         } else {
>           _display(acr, defs.at(0), link: link)
85c85
< // Display acronym for the first time. 
---
> // Display acronym for the first time.
88c88
<     display(acr, [#acrlpl(acr) (#acr\s)], link: link)
---
>     _display(acr, [#acrlpl(acr) (#acr\s)], link: link)
90c90
<     display(acr, [#acrl(acr) (#acr)], link: link)
---
>     _display(acr, [#acrl(acr) (#acr)], link: link)
107c107
< // Display acronym in the plural form. Expands it if used for the first time. 
---
> // Display acronym in the plural form. Expands it if used for the first time.
111c111,118
< #let print-index(title: "List of Abbreviations", sorted: "up", delimiter: ":", acr-col-size: 20%, level: 1) = {
---
> #let print-index(
>   title: "List of Abbreviations",
>   sorted: "up",
>   delimiter: ":",
>   acr-col-size: 20%,
>   level: 1,
>   outlined: false,
> ) = {
130c137
< }
\ No newline at end of file
---
> }
diff '--color=auto' -r 0.1.0/typst.toml 0.1.1/typst.toml
3c3
< version="0.1.0"
---
> version="0.1.1"
5c5,8
< authors=["@Julian702"]
---
> authors=[
>     "@Julian702",
>     "Gaetan Lepage @GaetanLepage"
> ]
10c13
< categories=["model"]
\ No newline at end of file
---
> categories=["model"]
```

**Comment by laurmaedje** [comment]
Since the package was originally submitted by @Julian702, this would require their approval.

**Comment by Julian702** [comment]
I'm currently writing my bachelor thesis. Is it fine if I have a look on Monday or Tuesday after I submitted?

**Comment by laurmaedje** [comment]
Sure, it's all fully up to you.

**Comment by GaetanLepage** [comment]
Definitely, take your time @Julian702 :)

**Review by Julian702 — APPROVED** [review]

**Pull request merged**
