### PR TITLE
sourcerer:0.2.0

### PR DESCRIPTION
**Pull request by miestrode**
I am submitting
- [ ] a new package
- [x] an update for a package

Description: Fixed the `README.md`, fixed rendering bugs with the `lang-box`, readded (apparently it was lost) the code that makes `lang` optional, simplified backend and allowed the line range used to take on a value of `auto` for one or both of the line numbers supplied, to create ranges such as `..x` and `x..`.

### CODE REVIEW

**Comment by miestrode** [comment]
Just issued a fixup. Apparently my implementation was a bit wrong, and also the version in the configuration file was wrong.

**Comment by laurmaedje** [comment]
Something is off with the diff:

image

If you want to submit changes to sourcerer:0.1.0 under the minor fix policy, please do that separately from sourcerer:0.2.0. (Although, if it's just docs fixes, I think it's not really necessary at all since the changes are in 0.2.0.)

**Comment by miestrode** [comment]
Yeah, I've noticed the diff thing. I just assumed it was some kind of bug, as I didn't make any changes in these. I'll sync my fork.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
