### PR TITLE
typst-ifsc:0.1.0

### PR DESCRIPTION
**Pull request by gabrielluizep**
I am submitting
- [x] a new package
- [ ] an update for a package

Adding a Typst templates for [Federal Institute of Santa Catarina](https://www.ifsc.edu.br/).

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [ ] `exclude`d PDFs or README images, if any, but not the LICENSE

- [x] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by gabrielluizep** [comment]
Should I was checking the other templates added to the repo, and I noticed that every template has its own package.

I think I misunterstood the idea, will create a new pull request with the correct way, one template per package.

**Comment by reknih** [comment]
Thanks for being the first person to submit a template!

We had a quick look and have the following tips:
- Generally, you are right that this should be multiple template packages rather than a big one
- The two presentation templates can remain a single package, you should be able to switch between the themes with a show rule parameter
- The template's entrypoint file should define a show rule as you did in your examples. Basically, the templates _are_ the examples.
- The assignment seems to be empty
- The package names need to be adjusted. They must not contain the string `typst` and need to be more unique in case another member of IFSC wants to publish their own, see the README of this repo.

**Comment by gabrielluizep** [comment]
Thanks! Will fix these points and submit a new PR!

**Comment by gabrielluizep** [comment]
Created new PR #409

**Pull request closed without merging**
