### PR TITLE
note-me:0.1.0

### PR DESCRIPTION
**Pull request by FlandiaYingman**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: Adds GitHub-style Admonitions (Alerts) to Typst.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

### CODE REVIEW

**Comment by laurmaedje** [comment]
It would be great if you could pick a bit more unique name. As is, it is a very obvious name for a package with this functionality, which we disallow to ensure level playing grounds for multiple people creating packages for the same thing.

**Comment by FlandiaYingman** [comment]
@laurmaedje Got it. Then how about `github-admonish`?

**Comment by laurmaedje** [comment]
That's similarly descriptive I would say. Ideally pick something creative and fun. You can take a look at https://typst.app/docs/packages for inspiration.

**Comment by FlandiaYingman** [comment]
Oh... I started to understand what you'd meant. Would it be better to use something like `note-me`?

**Comment by laurmaedje** [comment]
That would work!

**Comment by FlandiaYingman** [comment]
OK. Done

**Comment by laurmaedje** [comment]
Great, thanks!

**Pull request merged**
