### PR TITLE
teig:0.1.0

### PR DESCRIPTION
**Pull request by SolidTux**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: This plugin exposes a function that calculates eigenvalues of a given matrix. This can be useful to avoid accidental mistakes when writing about concrete matrices and their eigenvalues.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

### CODE REVIEW

**Comment by SolidTux** [comment]
Oops, forgot to make the repository public, that should be fixed now.

**Comment by elegaanz** [comment]
Thank you!

**Comment by laurmaedje** [comment]
The `authors` key is missing, but it is required for submissions. For some reason, CI didn't catch that, but it causes problems in Typst Universe. 

Package metadata can be changed through a minor fix PR. I've [added](https://github.com/typst/packages/commit/e17c4880aaad8689f5ee18d8327e59648251adeb) `authors = ["SolidTux"]` for now, so that it works in Typst Universe. Feel free to make an adjustment PR to another name than your GitHub username.

@elegaanz Could you enforce the existence of the authors array in CI?

**Comment by elegaanz** [comment]
Oops, sorry I didn't catch that. I will make sure the review bot checks for that array.

**Pull request merged**
