### PR TITLE
nth:0.1.0

### PR DESCRIPTION
**Pull request by extua**
I am submitting
- [x] a new package
- [ ] an update for a package

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name in conformance with the guidelines
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] ensured that my submission does not infringe upon the rights of a third party
- [x] tested my package locally on my system and it worked
- [x] named this PR as `name:version` of the submitted package
- [x] agree that my package will not be removed without good reason

Description:

This package adds a basic function to Typst for automatically appending 'st/nd/rd/th' to english ordinal numbers. It tries to provide the same functionality as the [nth macro](https://ctan.org/pkg/nth) for LaTeX.

### CODE REVIEW

**Comment by extua** [comment]
I've realised there's a bug here after reading the original TeX macro more closely. The suffix depends on the last _two_ digits.

For example, `#nth(11)` should show 11<sup>th</sup>, not 11<sup>st</sup>.

**Comment by laurmaedje** [comment]
Do you want me to postpone merging this until the regex issues are resolved?

**Comment by extua** [comment]
Thanks, yes best to hold off on merging this until `ends_with` is fixed.

**Comment by extua** [comment]
I've tested this with the latest development version of Typst (97ca009b), since the fix to ```ends_with``` was merged, and this package works fine now.

**Comment by laurmaedje** [comment]
Still probably best to wait until that's released in 0.8.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
