### PR TITLE
clatter:0.1.0

### PR DESCRIPTION
**Pull request by Gowee**
I am submitting
- [x] a new package
- [ ] an update for a package

Description: The package provides a PDF417 barcode generator.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

- [ ] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by Enter-tainer** [comment]
btw there is also https://typst.app/universe/package/tiaoma which supports pdf417

**Comment by Gowee** [comment]
> btw there is also https://typst.app/universe/package/tiaoma which supports pdf417
Wow. That is what I looked for, for months.

It would be great if there is a list of supported code in the README for users to search.

**Comment by elegaanz** [comment]
Could you change the version number to something that is not all zeroes, please? Other than that I looks good :)

**Comment by Gowee** [comment]
@elegaanz Changed to 0.1.0. :-)

**Comment by elegaanz** [comment]
Thank you :)

**Pull request merged**
