### PR TITLE
dragonling:0.1.0

### PR DESCRIPTION
**Pull request by coljac**
I am submitting
- [X] a new package

I have read and followed the submission guidelines and, in particular, I
- [X] selected a name in conformance with the guidelines
- [X] added a `typst.toml` file with all required keys
- [X] added a `README.md` with documentation for my package
- [X] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [X] ensured that my submission does not infringe upon the rights of a third party
- [X] tested my package locally on my system and it worked
- [X] named this PR as `name:version` of the submitted package
- [X] agree that my package will not be removed without good reason

This is a template for making modules for the Dungeons & Dragons roleplaying game. It implements the conventional styles that make it suitable for producing content for publication on official websites and elsewhere.

### CODE REVIEW

**Comment by laurmaedje** [comment]
We want to make the experience of using template packages as straight-forward as possible, with the possibility of providing a project template and selecting among templates in the the template gallery. So, I would hold off on merging this like with #36 and #84. Tempalte support shouldn't be too far out.

**Comment by coljac** [comment]
Perhaps the documentation could be modified to make the distinction between packages and templates clear, and to outline the (coming) procedure for both? I assume packages are to provide utility methods for inclusion in arbitrary documents, and templates are focused on producing documents that conform to a particular style, even though both are implemented in similar ways.

**Comment by laurmaedje** [comment]
There's a small note in the Readme, but it indeed doesn't go into the distinction. I'll look into it.

**Comment by laurmaedje** [comment]
@coljac I added a bit more explanation to the Readme.

**Comment by coljac** [comment]
Once the template system is in place I will resubmit this in the correct manner, along with some other templates that may benefit the community.

**Pull request closed without merging**
