### PR TITLE
haw-hamburg-bachelor-thesis:0.3.1, haw-hamburg-master-thesis:0.3.1, haw-hamburg-report:0.3.1 and haw-hamburg:0.3.1

### PR DESCRIPTION
**Pull request by LasseRosenow**
I am submitting
- [ ] a new package
- [x] an update for a package

Description: 
- Fix typst 0.12 compatibility
- Update glossarium to 0.5.1

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

- [x] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

### CODE REVIEW

**Comment by LasseRosenow** [comment]
The ci fails because the templates depend on haw-hamburg 0.3.1 which is also updated in this PR

**Comment by elegaanz** [comment]
I think calls to `register-glossary` are missing in `haw-hamburg-bachelor-thesis`: it fails to compile on my machine because references to glossary terms and abbreviations are not found.

**Comment by LasseRosenow** [comment]
Oh nooo you are correct I totally missed that one 😬 Thank you for pointing it out! :):)

I will fix it ASAP

**Comment by LasseRosenow** [comment]
Okay I fixed it and squashed it

**Comment by elegaanz** [comment]
Thanks!

**Pull request merged**
