### PR TITLE
codly: Fix icon name in example

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by Leedehai** [comment]
Hi - wondering if you could modify the PR title so it relates to the package? :)

**Comment by domoritz** [comment]
Done.

**Comment by laurmaedje** [comment]
This would require @Dherse's approval.

**Comment by Dherse** [comment]
I would suggest opening a pr on my repo so that I don't need to sync it with the packages repo

**Comment by domoritz** [comment]
Done in https://github.com/Dherse/codly/pull/6

**Comment by laurmaedje** [comment]
As I understood things, this should be closed and the fix will just be delivered through a normal update with the next codly version. If that isn't what was intended, just tell me.

**Pull request closed without merging**
